services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda13
    ports:
      - 8080:8080
    volumes:
      - ./models:/models
    command: --host 0.0.0.0 --port 8080 -m /models/Qwen3.5-9B.q5_k_m.gguf --alias "Qwen3.5-9B" -ngl 99 --ctx-size 32768 --jinja